### ISSUE TITLE
А каким образом генерируется books.json файл? Как его создать с нуля?

### ISSUE THREAD

**Issue by MrLokans** [theasder/access_books#9]

**Comment by theasder** [comment]
Отправляются (количество постов)/100 API запросов, вытягиваются оттуда массивы из записей, конкатинируются в один, сортируются по лайкам.

**Comment by MrLokans** [comment]
А есть ли скрипт, чтобы можно было включить его в репозиторий?

**Comment by theasder** [comment]
Серверное приложение, но можно в обычную утилиту переделать.
